################################################
#  AsciiDoc Package for Sublime Text 4:        #
#  https://github.com/tajmone/ST4-Asciidoctor  #
################################################

dist: trusty

git:
  depth: false

install:
  - npm install -g eclint

script:
  # ==============================================
  # EditorConfig Code Styles Validation via EClint
  # ==============================================
  # https://editorconfig.org
  # https://www.npmjs.com/package/eclint
  - bash ./validate.sh

# ///////////////////////////// ORIGINAL SETTINGS //////////////////////////////

# language: python
# sudo: false
# python: 3.3
# install: script/bootstrap.sh
# script: script/test.sh

# ------------------------------------------------------------------------------
# The original configuration no longer works on Travis CI, failing with:

## Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/python-3.3.tar.bz2
## $ curl -sSf --retry 5 -o python-3.3.tar.bz2 ${archive_url}
## curl: (22) The requested URL returned error: 404 Not Found
## Unable to download 3.3 archive. The archive may not exist.
## Please consider a different version.
