= Color Schemes

SublimeText ships with five default colors schemes: "`Breakers,`" "`Celeste,`" "`Mariana,`" "`Monokai,`" and "`Sixteen.`"
They all only have minimal support for colorizing markup files.
That is, none of them are nuanced in the particulars imparted by our AsciiDoc syntax specification.

This package, therefore, ships with a dedicated color scheme ("`AsciiDoc Dark`") which takes full advantage of this package's AsciiDoc syntax specification.
For example, the "`Molokai`", "`Breakers`", and "`Celeste`" color schemes that ship with ST4 do not bother to highlight the list bullets, nor the fences around tables, nor any of the markers that start and end various blocks (examples, sidebar, etc.).
This "`AsciiDoc Dark`" scheme does.
It is associated with AsciiDoc files by default (according to the _color_scheme_ setting in our `Asciidoctor.sublime-settings` file).


== Choosing a Different AsciiDoc-Specific Color Scheme

If you don't like the "`AsciiDoc Dark`" scheme, you can easily override it and pick a different color scheme to associate with AsciiDoc files.
(In the future, we may provide alternative schemes tailored to AsciiDoc, or you can roll your own.)

. Open an AsciiDoc file for editing (i.e. any file with an `.asciidoc` or `.adoc` extension).
. Pull down the `Preferences` menu and choose `Settings - Syntax Specific` (while the tab with the AsciiDoc file has focus).
. SublimeText will open in another window and show a split screen view. On the left is a tab labeled `Preferences.sublime-settings`, while the one on the right is labeled `Asciidoctor.sublime-settings`. The left pane is read-only. The right pane is editable.
. The contents of the right pane may or may not be empty to start. This represents your user-specific override settings for AsciiDoc files.
. Find the "color_scheme" setting on the left and click the pencil icon next to it. This will copy that "color_scheme" setting to the right. (Don't be confused if it doesn't say `AsciiDoc Dark.sublime-color-scheme`. It will likely show you the main default color scheme, which is `Mariana.sublime-color-scheme`.)
. Edit the "color_scheme" setting on the right to specify a color scheme of your liking (i.e. change `Mariana.sublime-color-scheme` to `My-Favorite-Scheme.sublime-color-scheme`.

CAUTION: Do not specify any folder names. Just give the name of the scheme file alone (`My-Favorite-Scheme.sublime-color-scheme`). SublimeText will find it automatically, wherever it resides.

When you save your changes, it will create (or update) a file called `Asciidoctor.sublime-settings` in your `User` package. FYI, you can open that file directly at any time by pulling down `Preferences` -> `Package Settings` -> `Asciidoctor` -> `Settings - User`.

NOTE: Setting an AsciiDoc-specific color scheme is distinctly different than pulling down the `Preferences` menu and choosing `Select Color Scheme...`. That sets the default color scheme that is used for plain text files (and any other file types that don't have a specific color scheme associated with them). The `Select Color Scheme...` command is simply a shortcut for editing the _color_scheme_ setting in the `Preferences.sublime-settings` file in your `User` package.


== A Note for Contributors

Since this package is still very much under development, it is important that collaborators use an AsciiDoc-specific color scheme in order to appreciate/experience/test the syntax highlighting nuances.
Many elements of the AsciiDoc syntax rely on (fine-grained) scope names which are peculiar to AsciiDoc, and very unlikely to be covered by general-purpose color schemes designed for programming languages or lightweight markup syntaxes (like Markdown, reST, etc.).


